### ISSUE TITLE
Decode the base64 encoded data - especially the data that was NLP'd

### ISSUE THREAD

**Issue by ewill00** [Alvearie/patient-browser#20]
When showing DiagnosticReports or Document References, it would be nice to be able to see the actual  text not the base64 encoded data.

When showing the evidence for a condition/medication that is derived from NLP running against the unstrutured text, the data is decoded and shown.

May need to discuss the best way to do this - not all base64 data is important, but it would be nice to read it within the UI vs opening up a decoder separately.

**Comment by mcbride-p** [comment]
Implemented by PR -> https://github.com/Alvearie/patient-browser/pull/28
